/**
 * Realistic Operational Mock Data for SocialOps SaaS Platform
 * All dates and records are structured to reflect an enterprise social media operations suite.
 */

export const INITIAL_POSTS = [
  {
    id: "post_101",
    title: "Introducing v2.4 of our API Gateway",
    content: "We just rolled out v2.4 of our low-latency API gateway. Throughput increased by 38% with sub-10ms p99 latency across all edge regions. Read the full engineering breakdown on our tech blog: https://acme.io/blog/gateway-v2-4 #Engineering #DevOps #Performance",
    platform: "X",
    account: "@acme_eng",
    scheduledAt: "2026-09-26T14:00:00.000Z",
    status: "Scheduled",
    campaign: "Q3 Engineering",
    mediaUrl: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=800&q=80",
    tags: ["Engineering", "DevOps", "Infrastructure"],
    views: 4520,
    likes: 218,
    reposts: 42,
    createdAt: "2026-09-25T10:15:00.000Z",
  },
  {
    id: "post_102",
    title: "Customer Spotlight: How FinTech scaleup cut cloud spend 42%",
    content: "Thrilled to share how our customer reduced monthly egress costs by 42% while simultaneously scaling to 15,000 active concurrent connections. Special thanks to the infra architecture team for spearheading this initiative. Link to the case study in the comments below.",
    platform: "LinkedIn",
    account: "Acme Cloud Technologies",
    scheduledAt: "2026-09-26T16:30:00.000Z",
    status: "Scheduled",
    campaign: "Customer Stories",
    mediaUrl: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=800&q=80",
    tags: ["FinTech", "Cloud", "CaseStudy"],
    views: 8940,
    likes: 412,
    reposts: 58,
    createdAt: "2026-09-25T11:20:00.000Z",
  },
  {
    id: "post_103",
    title: "Behind the Scenes: Product Sprint Demo Day",
    content: "Behind the screens at our bi-weekly Sprint Showcase! The distributed engineering crew shipped 14 new customer-requested features this sprint. What feature are you most eager to test next?",
    platform: "Instagram",
    account: "@acmelabs",
    scheduledAt: "2026-09-26T18:00:00.000Z",
    status: "Pending Review",
    campaign: "Culture & Team",
    mediaUrl: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=800&q=80",
    tags: ["Culture", "Teamwork", "TechLife"],
    views: 1200,
    likes: 85,
    reposts: 0,
    createdAt: "2026-09-25T14:40:00.000Z",
  },
  {
    id: "post_104",
    title: "Critical Security Advisory Notice",
    content: "Urgent Maintenance Completed: Security patch CVE-2026-9811 deployed across all cluster nodes. Zero downtime recorded. Review the advisory report in our compliance portal.",
    platform: "Slack",
    account: "#announcements",
    scheduledAt: "2026-09-26T11:00:00.000Z",
    status: "Published",
    campaign: "Operations",
    mediaUrl: null,
    tags: ["Security", "Patch", "Maintenance"],
    views: 310,
    likes: 45,
    reposts: 12,
    createdAt: "2026-09-26T10:50:00.000Z",
  },
  {
    id: "post_105",
    title: "Quarterly Townhall Highlights & Live AMA",
    content: "Catch the recording of our Q3 Executive Townhall. CEO & Head of Product discuss roadmap milestones, multi-cloud expansion, and upcoming developer SDK releases.",
    platform: "Facebook",
    account: "Acme Platform Official",
    scheduledAt: "2026-09-25T19:00:00.000Z",
    status: "Published",
    campaign: "Brand Awareness",
    mediaUrl: "https://images.unsplash.com/photo-1515187029135-18ee286d815b?auto=format&fit=crop&w=800&q=80",
    tags: ["Townhall", "ProductRoadmap"],
    views: 3410,
    likes: 198,
    reposts: 24,
    createdAt: "2026-09-24T12:00:00.000Z",
  },
  {
    id: "post_106",
    title: "Weekly Developer Tips: Zero-Allocation Buffers in Rust",
    content: "Tip of the week: Using zero-copy ring buffers can shave up to 3ms off high-frequency websocket serialization. Example snippet included in this thread. What's your go-to memory optimization trick?",
    platform: "Telegram",
    account: "Acme Dev Channel",
    scheduledAt: "2026-09-27T09:00:00.000Z",
    status: "Draft",
    campaign: "Developer Community",
    mediaUrl: null,
    tags: ["Rust", "Tips", "WebSockets"],
    views: 0,
    likes: 0,
    reposts: 0,
    createdAt: "2026-09-25T16:00:00.000Z",
  },
  {
    id: "post_107",
    title: "Instagram Carousel: 5 Cloud Architecture Traps to Avoid",
    content: "Avoid these 5 common architectural pitfalls when migrating microservices to Kubernetes clusters. Swipe through for the full breakdown. Save this post for your next architecture review! ⚡",
    platform: "Instagram",
    account: "@acmelabs",
    scheduledAt: "2026-09-25T13:30:00.000Z",
    status: "Failed",
    failureReason: "Instagram Graph API token expired (OAuthException 190). Re-authentication required.",
    campaign: "Q3 Engineering",
    mediaUrl: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=800&q=80",
    tags: ["Cloud", "Microservices", "Kubernetes"],
    views: 0,
    likes: 0,
    reposts: 0,
    createdAt: "2026-09-25T08:00:00.000Z",
  },
  {
    id: "post_108",
    title: "We are hiring Staff Distributed Systems Engineers",
    content: "We're expanding our Core Platform team. Looking for senior & staff engineers passionate about distributed concensus, Raft protocols, and high-availability database engines. Remote-first with global hubs.",
    platform: "LinkedIn",
    account: "Acme Cloud Technologies",
    scheduledAt: "2026-09-28T15:00:00.000Z",
    status: "Paused",
    campaign: "Hiring 2026",
    mediaUrl: "https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&w=800&q=80",
    tags: ["Careers", "Hiring", "Engineering"],
    views: 0,
    likes: 0,
    reposts: 0,
    createdAt: "2026-09-25T17:30:00.000Z",
  }
];

export const INITIAL_QUEUE = [
  {
    queueOrder: 1,
    id: "post_101",
    title: "Introducing v2.4 of our API Gateway",
    platform: "X",
    account: "@acme_eng",
    publishTime: "Today at 02:00 PM",
    timeRemaining: "2 hours 15 mins",
    status: "Scheduled",
  },
  {
    queueOrder: 2,
    id: "post_102",
    title: "Customer Spotlight: How FinTech scaleup cut cloud spend 42%",
    platform: "LinkedIn",
    account: "Acme Cloud Technologies",
    publishTime: "Today at 04:30 PM",
    timeRemaining: "4 hours 45 mins",
    status: "Scheduled",
  },
  {
    queueOrder: 3,
    id: "post_103",
    title: "Behind the Scenes: Product Sprint Demo Day",
    platform: "Instagram",
    account: "@acmelabs",
    publishTime: "Today at 06:00 PM",
    timeRemaining: "6 hours 15 mins",
    status: "Pending Review",
  },
  {
    queueOrder: 4,
    id: "post_106",
    title: "Weekly Developer Tips: Zero-Allocation Buffers in Rust",
    platform: "Telegram",
    account: "Acme Dev Channel",
    publishTime: "Tomorrow at 09:00 AM",
    timeRemaining: "21 hours",
    status: "Draft",
  },
  {
    queueOrder: 5,
    id: "post_108",
    title: "We are hiring Staff Distributed Systems Engineers",
    platform: "LinkedIn",
    account: "Acme Cloud Technologies",
    publishTime: "Sep 28, 2026 at 03:00 PM",
    timeRemaining: "2 days",
    status: "Paused",
  }
];

export const CONNECTED_ACCOUNTS = [
  {
    id: "acc_1",
    platform: "X",
    displayName: "Acme Engineering",
    handle: "@acme_eng",
    status: "Connected",
    lastSync: "3 minutes ago",
    rateLimitRemaining: "284 / 300 requests",
    tokenExpiry: "Active (OAuth 2.0 PKCE)",
    managedVia: "Swytchcode X Connector",
  },
  {
    id: "acc_2",
    platform: "LinkedIn",
    displayName: "Acme Cloud Technologies",
    handle: "urn:li:organization:918231",
    status: "Connected",
    lastSync: "8 minutes ago",
    rateLimitRemaining: "492 / 500 requests",
    tokenExpiry: "Expires in 58 days",
    managedVia: "LinkedIn Marketing v2",
  },
  {
    id: "acc_3",
    platform: "Instagram",
    displayName: "Acme Labs",
    handle: "@acmelabs",
    status: "Error",
    lastSync: "2 hours ago",
    rateLimitRemaining: "0 / 200 requests",
    tokenExpiry: "Token Expired (OAuthException 190)",
    managedVia: "Meta Graph API v21.0",
  },
  {
    id: "acc_4",
    platform: "Facebook",
    displayName: "Acme Platform Official",
    handle: "facebook.com/acmeplatform",
    status: "Connected",
    lastSync: "14 minutes ago",
    rateLimitRemaining: "920 / 1000 requests",
    tokenExpiry: "Active",
    managedVia: "Swytchcode Social Core",
  },
  {
    id: "acc_5",
    platform: "Telegram",
    displayName: "Acme Developer Channel",
    handle: "@acmedev_official",
    status: "Connected",
    lastSync: "1 minute ago",
    rateLimitRemaining: "Unlimited (Bot API)",
    tokenExpiry: "Active",
    managedVia: "Telegram Bot API v7.4",
  },
  {
    id: "acc_6",
    platform: "Slack",
    displayName: "Acme HQ Workspace",
    handle: "#announcements",
    status: "Connected",
    lastSync: "5 minutes ago",
    rateLimitRemaining: "Standard Tier",
    tokenExpiry: "Active (Bot Token)",
    managedVia: "Swytchcode Webhooks",
  }
];

export const AUTOMATION_JOBS = [
  {
    id: "job_01",
    name: "Publish Scheduled Posts",
    command: "node jobs/publish.js --queue --strict",
    schedule: "Every 5 minutes",
    lastExecution: "2 minutes ago (Exit 0)",
    nextExecution: "in 3 minutes",
    status: "Running",
    avgDuration: "420ms",
    executionsToday: 288,
    failuresToday: 0,
  },
  {
    id: "job_02",
    name: "Swytchcode Sync & Channel Poller",
    command: "node jobs/swytchcode-sync.js --live",
    schedule: "Every 10 minutes",
    lastExecution: "4 minutes ago (Exit 0)",
    nextExecution: "in 6 minutes",
    status: "Running",
    avgDuration: "780ms",
    executionsToday: 144,
    failuresToday: 0,
  },
  {
    id: "job_03",
    name: "Analytics & Engagement Collector",
    command: "node jobs/sync-metrics.js --deep",
    schedule: "Hourly at :00",
    lastExecution: "42 minutes ago (Exit 0)",
    nextExecution: "in 18 minutes",
    status: "Idle",
    avgDuration: "3.2s",
    executionsToday: 24,
    failuresToday: 1,
  },
  {
    id: "job_04",
    name: "Queue Slot Optimizer & Rebalancer",
    command: "node jobs/rebalance-queue.js",
    schedule: "Daily at 00:00 UTC",
    lastExecution: "11 hours ago (Exit 0)",
    nextExecution: "in 13 hours",
    status: "Idle",
    avgDuration: "180ms",
    executionsToday: 1,
    failuresToday: 0,
  },
  {
    id: "job_05",
    name: "Retry Failed Dispatches with Exponential Backoff",
    command: "node jobs/retry-failed.js --max-attempts 3",
    schedule: "Every 15 minutes",
    lastExecution: "7 minutes ago (Exit 1 - Token Error)",
    nextExecution: "in 8 minutes",
    status: "Error",
    avgDuration: "610ms",
    executionsToday: 96,
    failuresToday: 4,
  }
];

export const ACTIVITY_LOGS = [
  {
    id: "log_991",
    timestamp: "11:32:04 AM",
    level: "SUCCESS",
    action: "DISPATCH_POST",
    post: "Critical Security Advisory Notice",
    account: "#announcements",
    platform: "Slack",
    status: "Success",
    latency: "142ms",
    message: "Dispatched payload via Swytchcode Slack connector. Received status 200 OK with ts: 1727330524.0019",
  },
  {
    id: "log_992",
    timestamp: "11:30:18 AM",
    level: "ERROR",
    action: "DISPATCH_POST",
    post: "Instagram Carousel: 5 Cloud Architecture Traps",
    account: "@acmelabs",
    platform: "Instagram",
    status: "Failed",
    latency: "389ms",
    message: "HTTP 401 Unauthorized from Meta Graph API: Error validating access token: Session has expired on Sep 25, 2026.",
  },
  {
    id: "log_993",
    timestamp: "11:28:45 AM",
    level: "INFO",
    action: "QUEUE_POP",
    post: "Queue Job Worker tick",
    account: "System Worker",
    platform: "Internal",
    status: "Success",
    latency: "28ms",
    message: "Processed 0 pending queue items. Next scheduled trigger post_101 at 14:00:00 UTC.",
  },
  {
    id: "log_994",
    timestamp: "11:25:00 AM",
    level: "INFO",
    action: "SWYTCHCODE_SYNC",
    post: "Channel Health Check",
    account: "Swytchcode Daemon",
    platform: "All Channels",
    status: "Success",
    latency: "215ms",
    message: "Swytchcode sync completed successfully: 6 provider channels healthy, 1 channel reported expired credentials.",
  },
  {
    id: "log_995",
    timestamp: "11:15:22 AM",
    level: "WARN",
    action: "RATE_LIMIT_ALERT",
    post: "Token Threshold Warning",
    account: "@acme_eng",
    platform: "X",
    status: "Warning",
    latency: "45ms",
    message: "Hourly X API read limit is at 78% of tier ceiling. Backoff throttle adjusted to 500ms delay.",
  },
  {
    id: "log_996",
    timestamp: "10:55:10 AM",
    level: "SUCCESS",
    action: "CAMPAIGN_SYNC",
    post: "Q3 Engineering campaign metrics updated",
    account: "Analytics Engine",
    platform: "Cross-platform",
    status: "Success",
    latency: "1.2s",
    message: "Aggregated 14 posts across X, LinkedIn, Telegram. Total campaign impressions: 48,290.",
  }
];

export const CAMPAIGNS = [
  {
    id: "cmp_1",
    name: "Q3 Engineering Highlights",
    description: "Bi-weekly technical architecture breakdowns, benchmark releases, and developer updates.",
    platforms: ["X", "LinkedIn", "Telegram"],
    postsCount: 18,
    publishedCount: 14,
    startDate: "Jul 1, 2026",
    endDate: "Sep 30, 2026",
    status: "Active",
    impressions: "84.2K",
    engagementRate: "4.8%",
  },
  {
    id: "cmp_2",
    name: "Customer Stories & Enterprise ROI",
    description: "Case studies demonstrating cost savings, throughput gains, and enterprise reliability.",
    platforms: ["LinkedIn", "Facebook"],
    postsCount: 12,
    publishedCount: 9,
    startDate: "Aug 15, 2026",
    endDate: "Oct 15, 2026",
    status: "Active",
    impressions: "42.1K",
    engagementRate: "6.2%",
  },
  {
    id: "cmp_3",
    name: "Hiring & Engineering Culture 2026",
    description: "Employee spotlights, remote work culture, open roles for staff and principal engineers.",
    platforms: ["LinkedIn", "Instagram"],
    postsCount: 8,
    publishedCount: 4,
    startDate: "Sep 1, 2026",
    endDate: "Nov 30, 2026",
    status: "Active",
    impressions: "29.4K",
    engagementRate: "5.1%",
  },
  {
    id: "cmp_4",
    name: "Developer Community Q3 Sprint",
    description: "Open source tooling announcements, community tutorials, and Discord/Telegram engagement.",
    platforms: ["X", "Telegram", "Slack"],
    postsCount: 24,
    publishedCount: 24,
    startDate: "Jul 15, 2026",
    endDate: "Sep 20, 2026",
    status: "Completed",
    impressions: "112.5K",
    engagementRate: "7.4%",
  }
];

export const ANALYTICS_DATA = {
  overview: {
    postsPublished: 342,
    postsPublishedChange: "+14.2% vs last month",
    totalReach: "1.28M",
    totalReachChange: "+22.5% vs last month",
    impressions: "2.41M",
    impressionsChange: "+18.9% vs last month",
    totalEngagement: "89.4K",
    totalEngagementChange: "+9.1% vs last month",
    clicks: "34.8K",
    clicksChange: "+12.4% vs last month",
    avgEngagementRate: "5.4%",
    avgEngagementRateChange: "+0.6% vs benchmark",
  },
  dailyVelocity: [
    { day: "Mon", posts: 14, impressions: 38000 },
    { day: "Tue", posts: 18, impressions: 52000 },
    { day: "Wed", posts: 22, impressions: 64000 },
    { day: "Thu", posts: 26, impressions: 78000 },
    { day: "Fri", posts: 19, impressions: 49000 },
    { day: "Sat", posts: 8, impressions: 21000 },
    { day: "Sun", posts: 11, impressions: 29000 },
  ],
  platformBreakdown: [
    { platform: "LinkedIn", percentage: 42, reach: "537K", posts: 144, engagement: "6.8%" },
    { platform: "X", percentage: 31, reach: "396K", posts: 120, engagement: "4.2%" },
    { platform: "Instagram", percentage: 14, reach: "179K", posts: 42, engagement: "5.9%" },
    { platform: "Telegram", percentage: 8, reach: "102K", posts: 22, engagement: "8.1%" },
    { platform: "Facebook", percentage: 5, reach: "66K", posts: 14, engagement: "3.2%" },
  ]
};
