export const themes = [
  {
    name: "Nord Light",
    bg: "#ECEFF4",
    text: "#2E3440",
    muted: "#5E81AC",
    fontFamily: "'Inter', sans-serif",
    fontWeight: "800",
    letterSpacing: "-1px",
  },
  {
    name: "Soft Lavender",
    bg: "#FAF7FF",
    text: "#3B2F63",
    muted: "#8B7DB3",
    fontFamily: "'DM Serif Display', serif",
    fontWeight: "700",
    letterSpacing: "-1px",
  },
  {
    name: "Matcha",
    bg: "#F4F8F2",
    text: "#2D4A34",
    muted: "#6E8B74",
    fontFamily: "'Inter', sans-serif",
    fontWeight: "800",
    letterSpacing: "-1.5px",
  },
  {
    name: "Rose Quartz",
    bg: "#FFF5F7",
    text: "#4A2C38",
    muted: "#A36F83",
    fontFamily: "'Cormorant Garamond', serif",
    fontWeight: "700",
    letterSpacing: "-1px",
  },
  {
    name: "Sky Blue",
    bg: "#F2F8FF",
    text: "#163A5F",
    muted: "#6A8CB0",
    fontFamily: "'Space Grotesk', sans-serif",
    fontWeight: "800",
    letterSpacing: "-1.5px",
  },
  {
    name: "Champagne",
    bg: "#FFF9F0",
    text: "#3D3325",
    muted: "#A48B6A",
    fontFamily: "'Playfair Display', serif",
    fontWeight: "900",
    letterSpacing: "-1.5px",
  },
  {
    name: "Pearl",
    bg: "#FCFCFA",
    text: "#222222",
    muted: "#8C8C8C",
    fontFamily: "'Inter', sans-serif",
    fontWeight: "700",
    letterSpacing: "-1px",
  },
  {
    name: "Mint",
    bg: "#F2FFF9",
    text: "#0F5132",
    muted: "#74A892",
    fontFamily: "'IBM Plex Sans', sans-serif",
    fontWeight: "800",
    letterSpacing: "-1px",
  },
  {
    name: "Ocean Breeze",
    bg: "#F3FBFD",
    text: "#0F3D4C",
    muted: "#5F92A0",
    fontFamily: "'Manrope', sans-serif",
    fontWeight: "800",
    letterSpacing: "-1.5px",
  },
  {
    name: "Warm Sand",
    bg: "#FAF3E7",
    text: "#4A3A28",
    muted: "#A18B73",
    fontFamily: "'Libre Baskerville', serif",
    fontWeight: "700",
    letterSpacing: "-0.5px",
  },
  {
    name: "Tokyo Paper",
    bg: "#FCFBF7",
    text: "#2B2B2B",
    muted: "#7B7B7B",
    fontFamily: "'Noto Serif JP', serif",
    fontWeight: "700",
    letterSpacing: "-0.5px",
  },
  {
    name: "Sakura",
    bg: "#FFF7FA",
    text: "#52263F",
    muted: "#C08497",
    fontFamily: "'Cormorant Garamond', serif",
    fontWeight: "700",
    letterSpacing: "-1px",
  },
  {
    name: "Ice Blue",
    bg: "#F7FCFF",
    text: "#183153",
    muted: "#7A91B0",
    fontFamily: "'Inter', sans-serif",
    fontWeight: "800",
    letterSpacing: "-1px",
  },
  {
    name: "Coffee Cream",
    bg: "#FFF8F0",
    text: "#3E2C23",
    muted: "#9D7F68",
    fontFamily: "'Merriweather', serif",
    fontWeight: "700",
    letterSpacing: "-0.5px",
  },
  {
    name: "Pastel Peach",
    bg: "#FFF4ED",
    text: "#5A3422",
    muted: "#D18C6A",
    fontFamily: "'Poppins', sans-serif",
    fontWeight: "800",
    letterSpacing: "-1.5px",
  },
  {
    name: "Emerald Light",
    bg: "#F3FCF8",
    text: "#0B3D2E",
    muted: "#4F8A73",
    fontFamily: "'Inter', sans-serif",
    fontWeight: "900",
    letterSpacing: "-1.5px",
  },
  {
    name: "Linear",
    bg: "#FAFAFA",
    text: "#111111",
    muted: "#666666",
    fontFamily: "'Inter', sans-serif",
    fontWeight: "900",
    letterSpacing: "-2px",
  },
  {
    name: "Claude Style",
    bg: "#FDFBF7",
    text: "#2D2A26",
    muted: "#A16207",
    fontFamily: "'Source Serif 4', serif",
    fontWeight: "700",
    letterSpacing: "-0.5px",
  },
  {
    name: "OpenAI Light",
    bg: "#F7F7F5",
    text: "#202123",
    muted: "#10A37F",
    fontFamily: "'Inter', sans-serif",
    fontWeight: "800",
    letterSpacing: "-1px",
  },
  {
    name: "Luxury Gold",
    bg: "#FFFBF2",
    text: "#1F1A12",
    muted: "#B08D57",
    fontFamily: "'Playfair Display', serif",
    fontWeight: "900",
    letterSpacing: "-1.5px",
  },
].map((theme) => ({
  ...theme,
  accent: theme.accent || theme.muted,
  fontWeight: theme.fontFamily.includes("serif") ? "700" : "750",
  letterSpacing: "0px",
  fontSize: 31,
  lineHeight: 56,
  topicLineHeight: 36,
  topicGap: 112,
  brandGap: 34,
}));

export const brokenWingsThemes = [
  {
    name: "Midnight Calm",
    bg: "#0A0B10",
    text: "#FFFFFF",
    muted: "#CBD5E1",
    accent: "#E2E8F0",
    bgOverlayOpacity: 0.9,
    vignetteOpacity: 0.35,
    shadowOpacity: 0.95,
    titleColor: "#FFFFFF",
    bodyColor: "#FFFFFF",
    footerColor: "#CBD5E1",
    fontFamily: "'Georgia', 'Palatino', serif",
    topicFontFamily: "'Figtree', 'Inter', 'Segoe UI', 'Helvetica Neue', Arial, sans-serif",
    fontWeight: "500",
    topicFontWeight: "700",
    letterSpacing: "0px",
    topicLetterSpacing: "1px",
    topicTransform: "uppercase",
    bodyTransform: "none",
    bodyWeight: "500",
    bodySpacing: "0px",
    fontSize: 32,
    lineHeight: 54,
    topicFontSize: 20,
    topicLineHeight: 30,
    topicGap: 28,
    brandGap: 36,
    footerFontSize: 16,
    footerLetterSpacing: "1.5px",
    footerText: "being",
    maxBodyWidth: 900,
  },
  {
    name: "Pure Dark",
    bg: "#0D0D11",
    text: "#FFFFFF",
    muted: "#94A3B8",
    accent: "#F1F5F9",
    bgOverlayOpacity: 0.9,
    vignetteOpacity: 0.35,
    shadowOpacity: 0.95,
    titleColor: "#FFFFFF",
    bodyColor: "#FFFFFF",
    footerColor: "#94A3B8",
    fontFamily: "'Georgia', 'Palatino', serif",
    topicFontFamily: "'Figtree', 'Inter', 'Segoe UI', 'Helvetica Neue', Arial, sans-serif",
    fontWeight: "500",
    topicFontWeight: "700",
    letterSpacing: "0px",
    topicLetterSpacing: "1px",
    topicTransform: "uppercase",
    bodyTransform: "none",
    bodyWeight: "500",
    bodySpacing: "0px",
    fontSize: 32,
    lineHeight: 54,
    topicFontSize: 20,
    topicLineHeight: 30,
    topicGap: 28,
    brandGap: 36,
    footerFontSize: 16,
    footerLetterSpacing: "1.5px",
    footerText: "being",
    maxBodyWidth: 900,
  },
  {
    name: "Deep Slate",
    bg: "#080F18",
    text: "#FFFFFF",
    muted: "#CBD5E1",
    accent: "#E2E8F0",
    bgOverlayOpacity: 0.9,
    vignetteOpacity: 0.35,
    shadowOpacity: 0.95,
    titleColor: "#FFFFFF",
    bodyColor: "#FFFFFF",
    footerColor: "#CBD5E1",
    fontFamily: "'Georgia', 'Palatino', serif",
    topicFontFamily: "'Figtree', 'Inter', 'Segoe UI', 'Helvetica Neue', Arial, sans-serif",
    fontWeight: "500",
    topicFontWeight: "700",
    letterSpacing: "0px",
    topicLetterSpacing: "1px",
    topicTransform: "uppercase",
    bodyTransform: "none",
    bodyWeight: "500",
    bodySpacing: "0px",
    fontSize: 32,
    lineHeight: 54,
    topicFontSize: 20,
    topicLineHeight: 30,
    topicGap: 28,
    brandGap: 36,
    footerFontSize: 16,
    footerLetterSpacing: "1.5px",
    footerText: "being",
    maxBodyWidth: 900,
  },
  {
    name: "Night Film",
    bg: "#0B0B0D",
    text: "#FFFFFF",
    muted: "#E2E8F0",
    accent: "#FFFFFF",
    bgOverlayOpacity: 0.9,
    vignetteOpacity: 0.35,
    shadowOpacity: 0.95,
    titleColor: "#FFFFFF",
    bodyColor: "#FFFFFF",
    footerColor: "#CBD5E1",
    fontFamily: "'Georgia', 'Palatino', serif",
    topicFontFamily: "'Figtree', 'Inter', 'Segoe UI', 'Helvetica Neue', Arial, sans-serif",
    fontWeight: "500",
    topicFontWeight: "700",
    letterSpacing: "0px",
    topicLetterSpacing: "1px",
    topicTransform: "uppercase",
    bodyTransform: "none",
    bodyWeight: "500",
    bodySpacing: "0px",
    fontSize: 32,
    lineHeight: 54,
    topicFontSize: 20,
    topicLineHeight: 30,
    topicGap: 28,
    brandGap: 36,
    footerFontSize: 16,
    footerLetterSpacing: "1.5px",
    footerText: "being",
    maxBodyWidth: 900,
  },
].map((theme) => ({
  ...theme,
  accent: theme.accent || "#E2E8F0",
  fontWeight: "500",
  topicFontWeight: "700",
  bodyWeight: "500",
  letterSpacing: "0px",
  topicLetterSpacing: "1px",
  bodySpacing: "0px",
  fontSize: 32,
  lineHeight: 54,
  topicFontSize: 20,
  topicLineHeight: 30,
  topicGap: 28,
  brandGap: 36,
  footerFontSize: 16,
  footerLetterSpacing: "1.5px",
  footerText: "being",
  maxBodyWidth: 900,
  bgOverlayOpacity: 0.9,
  vignetteOpacity: 0.35,
  shadowOpacity: 0.95,
  topicTransform: "uppercase",
  bodyTransform: "none",
  titleColor: theme.titleColor || "#FFFFFF",
  bodyColor: "#FFFFFF",
  footerColor: theme.footerColor || "#CBD5E1",
}));

export const kanhaCodeThemes = [
  {
    name: "Deep Indigo & Pure Ivory",
    bg: "#0B2545",
    text: "#FFFFFF",
    muted: "#94A3B8",
    accent: "#FFFFFF",
    bgOverlayOpacity: 0.88,
    vignetteOpacity: 0.35,
    shadowOpacity: 0.92,
    titleColor: "#FFFFFF",
    bodyColor: "#FFFFFF",
    footerColor: "#CBD5E1",
    fontFamily: "'Georgia', 'Palatino', serif",
    topicFontFamily: "'Figtree', 'Inter', 'Segoe UI', 'Helvetica Neue', Arial, sans-serif",
    fontWeight: "500",
    topicFontWeight: "700",
    letterSpacing: "0px",
    topicLetterSpacing: "1px",
    topicTransform: "uppercase",
    bodyTransform: "none",
    bodyWeight: "500",
    bodySpacing: "0px",
    fontSize: 34,
    lineHeight: 56,
    topicFontSize: 20,
    topicLineHeight: 30,
    topicGap: 30,
    brandGap: 36,
    footerFontSize: 15,
    footerLetterSpacing: "1.5px",
    footerText: "KANHACODE  •  THE GITA DECODED",
    maxBodyWidth: 900,
  },
  {
    name: "Deep Teal Sanctuary",
    bg: "#071B20",
    text: "#FFFFFF",
    muted: "#94A3B8",
    accent: "#FFFFFF",
    bgOverlayOpacity: 0.87,
    vignetteOpacity: 0.34,
    shadowOpacity: 0.9,
    titleColor: "#FFFFFF",
    bodyColor: "#FFFFFF",
    footerColor: "#CBD5E1",
    fontFamily: "'Georgia', 'Palatino', serif",
    topicFontFamily: "'Figtree', 'Inter', 'Segoe UI', 'Helvetica Neue', Arial, sans-serif",
    fontWeight: "500",
    topicFontWeight: "700",
    letterSpacing: "0px",
    topicLetterSpacing: "1px",
    topicTransform: "uppercase",
    bodyTransform: "none",
    bodyWeight: "500",
    bodySpacing: "0px",
    fontSize: 34,
    lineHeight: 56,
    topicFontSize: 20,
    topicLineHeight: 30,
    topicGap: 28,
    brandGap: 36,
    footerFontSize: 15,
    footerLetterSpacing: "1.5px",
    footerText: "KANHACODE  •  GITA OPERATING SYSTEM",
    maxBodyWidth: 900,
  },
  {
    name: "Cosmic Blue Krishna",
    bg: "#081326",
    text: "#FFFFFF",
    muted: "#94A3B8",
    accent: "#FFFFFF",
    bgOverlayOpacity: 0.89,
    vignetteOpacity: 0.36,
    shadowOpacity: 0.94,
    titleColor: "#FFFFFF",
    bodyColor: "#FFFFFF",
    footerColor: "#CBD5E1",
    fontFamily: "'Georgia', 'Palatino', serif",
    topicFontFamily: "'Figtree', 'Inter', 'Segoe UI', 'Helvetica Neue', Arial, sans-serif",
    fontWeight: "500",
    topicFontWeight: "700",
    letterSpacing: "0px",
    topicLetterSpacing: "1px",
    topicTransform: "uppercase",
    bodyTransform: "none",
    bodyWeight: "500",
    bodySpacing: "0px",
    fontSize: 34,
    lineHeight: 56,
    topicFontSize: 20,
    topicLineHeight: 30,
    topicGap: 28,
    brandGap: 36,
    footerFontSize: 15,
    footerLetterSpacing: "1.5px",
    footerText: "KANHACODE  •  PRACTICAL DHARMA",
    maxBodyWidth: 900,
  },
  {
    name: "Midnight Temple",
    bg: "#0E1520",
    text: "#FFFFFF",
    muted: "#94A3B8",
    accent: "#FFFFFF",
    bgOverlayOpacity: 0.88,
    vignetteOpacity: 0.34,
    shadowOpacity: 0.92,
    titleColor: "#FFFFFF",
    bodyColor: "#FFFFFF",
    footerColor: "#CBD5E1",
    fontFamily: "'Georgia', 'Palatino', serif",
    topicFontFamily: "'Figtree', 'Inter', 'Segoe UI', 'Helvetica Neue', Arial, sans-serif",
    fontWeight: "500",
    topicFontWeight: "700",
    letterSpacing: "0px",
    topicLetterSpacing: "1px",
    topicTransform: "uppercase",
    bodyTransform: "none",
    bodyWeight: "500",
    bodySpacing: "0px",
    fontSize: 34,
    lineHeight: 56,
    topicFontSize: 20,
    topicLineHeight: 30,
    topicGap: 28,
    brandGap: 36,
    footerFontSize: 15,
    footerLetterSpacing: "1.5px",
    footerText: "KANHACODE  •  THE GITA DECODED",
    maxBodyWidth: 900,
  },
].map((theme) => ({
  ...theme,
  accent: theme.accent || "#FFFFFF",
  fontWeight: "500",
  topicFontWeight: "700",
  bodyWeight: "500",
  letterSpacing: "0px",
  topicLetterSpacing: "1px",
  bodySpacing: "0px",
  fontSize: 34,
  lineHeight: 56,
  topicFontSize: 20,
  topicLineHeight: 30,
  topicGap: 28,
  brandGap: 36,
  footerFontSize: 15,
  footerLetterSpacing: "1.5px",
  footerText: theme.footerText || "KANHACODE  •  THE GITA DECODED",
  maxBodyWidth: 900,
  bgOverlayOpacity: 0.88,
  vignetteOpacity: 0.34,
  shadowOpacity: 0.92,
  topicTransform: "uppercase",
  bodyTransform: "none",
  titleColor: "#FFFFFF",
  bodyColor: "#FFFFFF",
  footerColor: theme.footerColor || "#CBD5E1",
}));
